-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 12:56:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidades` (
  `cid_id` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cid_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `cod_uf` INT GENERATED ALWAYS AS (),
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`cod_uf`),
  UNIQUE INDEX `cod_uf_UNIQUE` (`cod_uf` ASC) VISIBLE,
  UNIQUE INDEX `UF_UNIQUE` (`UF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituicoes` (
  `inst_id` INT NOT NULL AUTO_INCREMENT,
  `nome_inst` VARCHAR(30) NOT NULL,
  `logradouro` VARCHAR(30) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(30) NULL,
  `cep` INT(9) NOT NULL,
  `cid_id` INT NOT NULL,
  `telefone` INT(11) NOT NULL,
  `website` VARCHAR(45) NULL,
  `cod_uf` INT NOT NULL,
  `metadata_sobre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`inst_id`),
  UNIQUE INDEX `inst_id_UNIQUE` (`inst_id` ASC) VISIBLE,
  INDEX `cod_uf_idx` (`cod_uf` ASC) VISIBLE,
  CONSTRAINT `cid_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`Cidades` (`cid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_uf`
    FOREIGN KEY (`cod_uf`)
    REFERENCES `mydb`.`UF` (`cod_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campanhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campanhas` (
  `camp_id` INT GENERATED ALWAYS AS (),
  `inst_id` INT NULL,
  `nome_camp` VARCHAR(30) NULL,
  `metadata_camp` VARCHAR(200) NULL,
  `data_ini` DATETIME NULL,
  `data_fin` DATETIME NULL,
  PRIMARY KEY (`camp_id`),
  UNIQUE INDEX `camp_id_UNIQUE` (`camp_id` ASC) VISIBLE,
  INDEX `inst_id_idx` (`inst_id` ASC) VISIBLE,
  CONSTRAINT `inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`Instituicoes` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hist_camp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hist_camp` (
  `hist_camp_id` INT GENERATED ALWAYS AS (),
  `user_id` INT NULL,
  `camp_id` INT NULL,
  `valor_doado` INT NULL,
  PRIMARY KEY (`hist_camp_id`),
  UNIQUE INDEX `hist_camp_id_UNIQUE` (`hist_camp_id` ASC) VISIBLE,
  INDEX `camp_id_idx` (`camp_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `mydb`.`Campanhas` (`camp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(8) NOT NULL,
  `Hist_camp_hist_camp_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_Usuario_Hist_camp1_idx` (`Hist_camp_hist_camp_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Hist_camp1`
    FOREIGN KEY (`Hist_camp_hist_camp_id`)
    REFERENCES `mydb`.`Hist_camp` (`hist_camp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doar_Campanhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doar_Campanhas` (
  `camp_id` INT GENERATED ALWAYS AS (),
  `inst_id` INT NULL,
  `user_id` INT NOT NULL,
  `valor_doado` INT NOT NULL,
  PRIMARY KEY (`camp_id`),
  UNIQUE INDEX `camp_id_UNIQUE` (`camp_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `inst_id_idx` (`inst_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`Instituicoes` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `mydb`.`Campanhas` (`camp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doar_Instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doar_Instituicoes` (
  `inst_id` INT NOT NULL,
  `user_id` INT NULL,
  `valor_doado` INT NULL,
  PRIMARY KEY (`inst_id`),
  UNIQUE INDEX `inst_id_UNIQUE` (`inst_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`Instituicoes` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Esquema_doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Esquema_doacoes` (
  `user_id` INT NOT NULL,
  `inst_id` INT NOT NULL,
  `data_doa` DATETIME NOT NULL,
  `valor_doado` INT NOT NULL,
  `valor_total_doado` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `inst_id_idx` (`inst_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`Instituicoes` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hist_inst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hist_inst` (
  `hist_inst_id` INT GENERATED ALWAYS AS (),
  `user_id` INT NULL,
  `inst_id` INT NULL,
  `valor_doado` INT NULL,
  PRIMARY KEY (`hist_inst_id`),
  UNIQUE INDEX `hist_camp_id_UNIQUE` (`hist_inst_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `inst_id_idx` (`inst_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`Instituicoes` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
